# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            tootmeet
tagline:          'tootmeet'
description:      'Mastodon community meetups'
url:              https://tootmeet.com
baseurl:          /

author:
  name:           'carrotcypher'
  url:            https://github.com/carrotcypher  

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
