# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            tootmeet
tagline:          'tootmeet'
description:      'Mastodon community meetups'
url:              https://tootmeet.com
baseurl:          /

author:
  name:           'carrotcypher'
  url:            https://github.com/carrotcypher  

gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
